<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.bookstore</groupId>
    <artifactId>bookstore-microservices</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Bookstore Microservices Aggregator</name>

    <!-- ONLY purpose: list modules -->
    <modules>
        <module>admin-service</module>
        <module>api-gateway</module>
        <module>cart-service</module>
        <module>config-server</module>
        <module>customer-details-service</module>
        <module>eureka-server</module>
        <module>feedback-service</module>
        <module>notification-service</module>
        <module>order-service</module>
        <module>product-service</module>
        <module>user-service</module>
        <module>wishlist-service</module>
    </modules>

</project>