server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #temoporarily disable service discovery for testing
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
#              filters:
#                - AuthenticationFilter   # comment this for testing

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/admin/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**,/api/products,/api/categories/**
#          filters:
#            - AuthenticationFilter

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthenticationFilter

        - id: wishlist-service
          uri: lb://WISHLIST-SERVICE
          predicates:
            - Path=/api/wishlist/**
          filters:
            - AuthenticationFilter

        - id: customer-details-service
          uri: lb://CUSTOMER-DETAILS-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/api/feedback/**
          filters:
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:bookstore-super-secret-key-2024-must-be-at-least-256-bits}