server:
  port: 8087

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://order-db:5432/order_db
    username: ${DB_USER:admin}
    password: ${DB_PASS:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092