server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://product-db:5432/product_db
    username: ${DB_USER:admin}
    password: ${DB_PASS:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
  instance:
    prefer-ip-address: true